### ISSUE TITLE
Missing library?

### ISSUE THREAD

**Issue by ikat123** [333fred/compiler-developer-sdk#4]
Hey, cool extension. I tried to compile and run it from source, but vscode complains about not being able to find 'operationTree/nodeAtRange' and 'syntaxTree/nodeAtRange'. 
I noticed that the extension downloaded from the store has two dlls:
**Microsoft.CodeAnalysis.CompilerDeveloperSdk.dll** , which I was able to build
and 
**Microsoft.CodeAnalysis.ExternalAccess.CompilerDeveloperSDK.dll** for which I don't see the source code in the repo.

After copying external access dll into my project folder, it works as expected again and I'm able to make some changes. But not being super familiar with LSP or vscode extensions, I'm not sure if this will stop me from adding new features at some point. 
Anyway, am I missing something? Or could you upload the source for that second dll pretty please?

**Comment by 333fred** [comment]
The second dll comes from roslyn. If you want to do local development, what is been doing is copying both the external access dll and the sdk dll from the bin folder of the sdk around as needed.

What are you looking to contribute?

**Comment by 333fred** [comment]
I'm going to close this out. Feel free to ask any more questions if you have them.
